- name: Ensuring we have duffy user
  user:
    name: "{{ duffy_user }}"
    comment: "Duffy App user"
  tags:
    - user

- name: Ensuring we have directories for Duffy
  file:
    state: directory
    owner: "{{ duffy_user }}"
    path: "{{ item }}"
  with_items:
    - "{{ duffy_app_basedir }}"
    - "{{ duffy_python_venv_path }}"
  tags:
    - directories

- name: Cloning/updating local duffy code from git
  git:
    repo: "{{ duffy_upstream_git_repo }}"
    dest: "{{ duffy_app_basedir }}"
      #version: "{{ duffy_git_version }}"
    force: yes
  become_user: "{{ duffy_user }}"
  become: True
  tags:
    - app

- name: install git, python3.8, virtualenv
  dnf:
    name:
      - git
      - python3-virtualenv
      - python38

- name: chdir
  command: "cd {{ duffy_python_venv_path }}"

- name: create a venv
  command: "virtualenv-3 {{ duffy_python_venv_path }} --python=python3.8"
  become_user: "{{ duffy_user }}"
  become: True
  tags:
    - app

- name: Install poetry
  pip:
    name: poetry
    virtualenv: "{{ duffy_python_venv_path }}"
  args:
    chdir: "{{ duffy_app_basedir }}"
  become_user: "{{ duffy_user }}"
  become: True
  tags:
    - app

- name: Install via poetry
  command: "{{ duffy_python_venv_path }}/bin/poetry install"
  args:
    chdir: "{{ duffy_app_basedir }}"
  become_user: "{{ duffy_user }}"
  become: True
  tags:
    - app
